spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    driverClassName: org.postgresql.Driver
    username: GABRIEL
    password: gabriel
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8000